name: lazy_forge
executables:
  lazy_forge: lazy_forge
description: IDE de terminal (TUI) em Dart para modelagem de schema com comandos, visualização em tempo real e export SQL.
version: 1.0.1
repository: https://github.com/dte005/lazy_forges
homepage: https://dte005.github.io/lazy_forges/#database-types
issue_tracker: https://github.com/dte005/lazy_forges/issues

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  nocterm: ^0.8.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
